### ISSUE TITLE
Physical Exam and Surgery Templates

### ISSUE THREAD

**Issue by fractious16** [carl-hamlin/barks#10]
Prewritten Exam and Surgery descriptions that Dr. Simko can insert into current visit annotation with 1 click.

They should be titled "Dr Simko PE", "Dr Simko OVH" and "Dr Simko Neuter". They will be modified and edited by Dr Simko during the visit.

**Comment by carl-hamlin** [comment]
Updated title and description. This issue is prioritized as a second stage issue - not necessary for minimum viable product, but severely nice to have. Look towards seeing these templates in the package around early June.

**Comment by carl-hamlin** [comment]
Fixed in e.47. Closing.
