### ISSUE TITLE
Rx Refill Subsystem

### ISSUE THREAD

**Issue by carl-hamlin** [carl-hamlin/barks#113]
While working on the new annotation stuff, Dr. Simko and I discussed Rx Refills at some length, and it became clear that we will not be able to completely address all of the issues associated with drug refills using the annotation system as coded.

The new proposal involves recording prescriptions and limiting the ability to do so to Doctors within the organization, and then selectively allowing refills of that same prescription on a per-client basis.

This issue very likely involves a new table for recording prior prescriptions and their associated instruction sets, along with allowed refills, as well as separating out prescribed drugs from over the counter drugs.

Fuck.

**Comment by carl-hamlin** [comment]
commit 2048643e532b671bda83fa002bb7e08284d1500a
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Oct 18 17:46:40 2019 -0700

    Enhancement 113:
    
    Maintenance commit for portability.
    
    Interface for adding prescriptions is pretty much in, data layer
    has some untested work, and this commit should *definitely* not be
    relied upon.

**Comment by carl-hamlin** [comment]
commit 8959ef2c7a82c9f3f86323750729921686903089 (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Oct 21 14:56:01 2019 -0700

    Enhancement 113:
    
    Presciptions may now be created through the interface, but not yet
    interacted with beyond the initial creation of the base visit.

**Comment by carl-hamlin** [comment]
commit d5268358fb92db867f953acb1f7207a7e0ce6d34 (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Oct 21 15:33:48 2019 -0700

    Enhancement 113:
    
    Prescriptions now show up on animals during caretaker load.

**Comment by carl-hamlin** [comment]
commit 1a91fc3f2fe6f86332a766eeba57f6a3a742cf61 (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Oct 21 16:09:08 2019 -0700

    Enhancement 113:
    
    Prescribable drugs now filter on prescribable flag in drugs table.

**Comment by carl-hamlin** [comment]
commit c585e76ba513b6b3450699d8df058cca9783bccd (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Oct 21 16:22:34 2019 -0700

    Enhancement 113:
    
    Prescribable drugs no longer show up on tech line item sheets.

**Comment by carl-hamlin** [comment]
commit 0a920b14a2a698997b7fe7839734ea7d5debdf88 (HEAD -> e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Oct 21 17:00:11 2019 -0700

    Enhancement 113:
    
    Button is in for animals with active prescriptions. No
    functionality yet, but the button knowns when it's supposed to
    show up, and when it isn't.
    
    This is not as simple a task as it sounds.

**Comment by carl-hamlin** [comment]
commit 5eaf9c8b82e36d69d6024a687855c697497a0f1f (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Oct 22 14:37:40 2019 -0700

    Enhancement 113:
    
    Previously added prescriptions may now be refilled.

**Comment by carl-hamlin** [comment]
commit 4ed7abe4eb719d114c513efd45824ee7c2e015fb (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Oct 23 12:59:45 2019 -0700

    Enhancement 113:
    
    Fixed access restrictions so that only folks authorized to build
    new prescriptions may do so, but everyone can refill them.

**Comment by carl-hamlin** [comment]
commit f842cfbcef5f90a64d710ee761710154812c148d (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Oct 24 16:30:11 2019 -0700

    Enhancement 113:
    
    Prescriptions (and other line items as well) now have optional
    instructions that can be filled in and which show up on the
    invoice.

**Comment by carl-hamlin** [comment]
commit 9de88fa2f55966142d00e381396e7b46a4455c8a (HEAD -> e.113, origin/e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Oct 24 16:38:38 2019 -0700

    Enhancement 113:
    
    Return messaging for new and refilled prescriptions no longer
    repeats itself unneccessarily.

**Comment by carl-hamlin** [comment]
commit bde4037bf07c4b497bbdfb8f50a22055dd6cce95 (origin/e.113, e.113)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Nov 1 17:07:40 2019 -0700

    Enhancement 113:
    
    Fixed error where zero refill prescriptions were retained by the
    system instead of being expunged.

**Comment by mogallie** [comment]
I am receiving  emails from Barks, I am sure you want to keep private. I am getting them on my yahoo account.

    On Friday, November 1, 2019, 05:10:48 PM PDT, Carl Hamlin <notifications@github.com> wrote:  
 
 
commit bde4037bf07c4b497bbdfb8f50a22055dd6cce95 (origin/e.113, e.113)
Author: Carlisle T. Hamlin hamlin.carlisle@gmx.com
Date: Fri Nov 1 17:07:40 2019 -0700
Enhancement 113:

Fixed error where zero refill prescriptions were retained by the
system instead of being expunged.
