### ISSUE TITLE
Update Client Phone and Address Info at Every Visit

### ISSUE THREAD

**Issue by fractious16** [carl-hamlin/barks#12]
2 contact phone numbers and current address must be requested during each visit. Flag intake screen to prompt reception to confirm this information.

**Comment by carl-hamlin** [comment]
Accidentally closed during new user tutorial. Re-opening.

**Comment by carl-hamlin** [comment]
So if I'm reading this correctly, you want a prompt on the search mechanism that asks the operator to request updated phone and address info, ne? If so, this is a relatively trivial tack-on and I could knock it out sometime during the week when I get a few minutes to rub together. Lemme know.

**Comment by carl-hamlin** [comment]
This issue is more than a year old and hasn't received any traction Closing until needed.
