### ISSUE TITLE
Visit Date Mismatch between Server and Local Time

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#121]

**Comment by carl-hamlin** [comment]
commit a3fc416e9c631c8ca1aa84367878c67d68cbc450 (origin/b.121, b.121)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Nov 15 13:22:03 2019 -0800

    Bugfix 121:
    
    Simplified dates for simple conversion utility on server.
    
    This problem will definitely have to be revisited for calendar
    integration, but for the moment this resolves the issue of dates
    being incorrectly converted as a result of differences between
    local time and server time.
