### ISSUE TITLE
Can I list (4)  Changes in one "issue"

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#132]
(1) client Kyle Smith pet Zeus picked up and Paid for Apoguel on 12/10, Doctor didnt know so she posted again on 12/12  please delete the 12/12 item

(2) Chris Allergi, please remove patient Midnight linked to the account:  I was searching midnights on his account and hit confirm link instead of cancel...oops

(3) Client Greg Stanley... Has an outstanding balance for 2 pets for Thyroxine.  It appears one of those was incorrectly posted to CJ that day and paid for but owner insists both were paid for at the time.  None the less at least one was paid for.

(4) Sharon Holbrook  paid by phone on 12/12/19...I remember calling her and getting the card but forgot to post the payment.

**Comment by Lenorebarton** [comment]
* (2)Chris Allegri

**Comment by carl-hamlin** [comment]
Kyle Smith's rogue Apoquel visit has been purged.

**Comment by carl-hamlin** [comment]
Midnight is no longer associated with Chris Allegri.

**Comment by carl-hamlin** [comment]
Greg Stanley does not appear to have a visit involving Thyroxine for CJ. Please clarify?

**Comment by carl-hamlin** [comment]
Sharon Holbrook's payment has been posted and backdated.

**Comment by Lenorebarton** [comment]
Re: Greg Stanley  If you check his invoice for 9/20/19,  you will see CJ  was charged for Rabies, Tri- heart, then the items below are for 120-unlisted item  $26.40  then another 120- unlisted item $24.00.  all these were paid for.  Same day, Thyroxin For Freddie and Riley were enter by Dr., in the same quantiy and price.  This represents the unpaid balance.  Does this make sense now?

**Comment by carl-hamlin** [comment]
Gotcha. Oy, veh, vadda clusterfuck.

It's unravelled now and his balance is zero. That's the last of the bunch.
