### ISSUE TITLE
3 Changes

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#134]
1)  Theresa Taylor  please change pet "Maya" to "Maia"

2) Rebecca Hazelton should be "Hazleton"

3) Stacie Jackie should be "Jacke"

**Comment by carl-hamlin** [comment]
In yet more news of the ridiculous, I've changed a 'y' into an 'i' for Theresa Taylor.

**Comment by carl-hamlin** [comment]
Rebecca's last name is now correctly spelled. Crisis averted.

**Comment by carl-hamlin** [comment]
That pesky 'i' has been removed for Stacy.
