### ISSUE TITLE
5 issues 

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#144]
1) Please change David Elzonzo to "Elzondo" 

2) Vic Manuelli please change "New Kitten" to "Pixie"

3) Gloria Wilkins Chanche "Kitten" to "Monster"

4) Delete client Claudette Graanucci She was added correctly as Claudette Granucci

5) Focas account please delete AID5427, 5428 and 5429 patients were added twice

**Comment by Lenorebarton** [comment]
6) (Just Found) on Suzy Serra please change "Steth" to "Mimi"

**Comment by carl-hamlin** [comment]
Henceforth, please use one issue number per issue.
