### ISSUE TITLE
Dee Dee Drake 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#145]
Please Change Gender For Gatsby From Female To Male.

**Comment by carl-hamlin** [comment]
There is no 'Gatsby' in the system.

**Comment by lwilsonbooth** [comment]
Feline under name : Gatsby A43596246
AID # 5438
In  Dee Dee Drake's Account.

**Comment by carl-hamlin** [comment]
Thank you. Gatsby A43596246 is now listed as male. Closing issue.
