### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#147]
1)   Steve Hall : please remove Luna (5448) Duplicate patients

2)   Vinni Bubak  please adjust balance of $13.50   the charge was transferref from cornerstone, but was an incorrect balance.  This was an incident in which a presciption was but into Cornerstone so a label could be printed but not zeroed out before closing the invoice.

3)Gloria Lorenzo (1746)  please delete this client.  Misspelled and added correctly at a later date.

**Comment by carl-hamlin** [comment]
Please stop re-adding clients when you misspell their names. It is orders of magnitude easier for me to change the spelling of a name, than it is for me to remove an entire client record.
