### ISSUE TITLE
Accidentally Added Client Twice. 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#148]
Please Remove Robert Norton With CID#2217. Accidentally Added Him Twice And Remove Pet, Oscar AID#5534 From Other CID#2215.

**Comment by carl-hamlin** [comment]
Robert Norton, CID2217 has been removed from the database.

**Comment by carl-hamlin** [comment]
Oscar, AID5534 has been removed from the database.

**Comment by carl-hamlin** [comment]
Henceforth, please label this kind of issue 'data-munge'. Closing issue.
