### ISSUE TITLE
Accidentally Added Pet Twice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#151]
Would you mind removing pet, "Lily" AID #5556 from Nancy Jauch's Account? Accidentally added the pet twice to her account. 
Also, Could You Remove pet, "Buddy" AID #4259 From Suzy Serra's Account? That pet was added twice as well.

**Comment by lwilsonbooth** [comment]
Would you mind removing two pets from Alain Canabou CID#58, Pet name Crawco AID#149 And Crawco AID#4440. This Dog was added three times. Thanks

**Comment by carl-hamlin** [comment]
Moving forward, please add each issue to it's own ticket.

**Comment by carl-hamlin** [comment]
Animal ID 5556 has been removed from the database.

**Comment by carl-hamlin** [comment]
Animal ID 4259 has been removed from the database.

**Comment by carl-hamlin** [comment]
Animal ID 149 has been removed from the database.

**Comment by carl-hamlin** [comment]
Animal ID 4440 has been removed from the database.
Closing issue.
