### ISSUE TITLE
Animal without #

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#154]
Please delele {Smoke} Samson canine Rott without ID #, Under Dee Dee Drake.

**Comment by carl-hamlin** [comment]
Why are we removing Samson?

**Comment by tlutzi** [comment]
Duplicate

**Comment by carl-hamlin** [comment]
RIP animal ID 5569. Moving forward, when you want me to make changes to existing info, please label your tickets with the 'data-munge' label. Closing issue.
