### ISSUE TITLE
Gender Entered Wrong

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#160]
I accidentally added Rocky's gender wrong in Barbel Francisco's account. Would you mind switching it from male to female? Thanks.

**Comment by carl-hamlin** [comment]
Moving forward, when you need me to change existing data, please label your ticket with the 'data-munge' label.

**Comment by carl-hamlin** [comment]
Additionally, when you need me to make changes to a specific animal, please include an animal ID.

**Comment by carl-hamlin** [comment]
Animal ID 5611 is now listed as female. Closing issue.
