### ISSUE TITLE
Price increased

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#162]
Client Elizabeth Wilden has been buyin Optimune for many months  the price doubled since her last purchase in December from 29.30 to 58.58.  this seems excessive noted several very large increases including Temeril P ,Cephelexin , Ampicillin  and other antibiotics   elizabeth Wilden would like a refund if this price is incorrect.

**Comment by carl-hamlin** [comment]
The new prices are correct. Dr. Simko and I monitor the pricing of goods as we make the purchases, and set prices accordingly. Please do keep us informed as to negative customer feedback concerning new pricing. Closing issue.
