### ISSUE TITLE
Sex change

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#163]
Client Dee Dee Drake animal Misty...   added as male, should be female.  My mistake.

**Comment by carl-hamlin** [comment]
Moving forward, when you need me to change existing data, please label your ticket 'data-munge'.

**Comment by carl-hamlin** [comment]
Additionally, please include an animal ID when you need changes to a specific animal. There are multiple 'Misty' animals under Drake.

**Comment by carl-hamlin** [comment]
The requested change is in. Closing issue.
