### ISSUE TITLE
Client Wont Load in Barks

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#168]
I added Mathew Wilson and his cat "Sid" but it wont load. I think I might have done something wrong? Would You mind fixing it?    03.09.2020

He has an appointment today so I will Add him twice, Hopefully you can delete the account that wont work.

**Comment by carl-hamlin** [comment]
Client ID 2333 was created with quotation marks in one of the fields. This *must* stop happening - I no longer have time to improve BARKS, and until I do, this input sanitization issue will never be fixed. Please be mindful of your input and do not use quotation marks until such time as I'm able to begin back end development of BARKS again, and fix the sanitization issue.

Client ID 2333 has been removed from the database. Closing issue.

**Comment by carl-hamlin** [comment]
Also - moving forward, when there is data in BARKS that you need me to change, please use the data-munge label.
