### ISSUE TITLE
Donna Palmer

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#170]
Cornerstone balance services date back to 3/2018  she said surgery failed and leg had to be amputated at the emergency hospital.  Dr Black told her he would adjust the balance, but it is still showing a balance due

**Comment by carl-hamlin** [comment]
Lenore, moving forward please use the data-munge label on issues that pertain to an adjustment to extant data.

**Comment by carl-hamlin** [comment]
Damn. That was a big balance, and we could have used the money. It's gone now. Closing issue.
