### ISSUE TITLE
Al Sterling

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#171]
Al Sterling was added into BARKS twice by accident. Would you mind removing CID 2344.

**Comment by carl-hamlin** [comment]
Loren.

Moving forward - please assign me and yourself to new issues, and if the issue pertains to a modification to extant data, please use the data-munge label.

**Comment by carl-hamlin** [comment]
RIP second Al Sterling and his dog 'Sparki'. Closing issue.
