### ISSUE TITLE
Christine Starks

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#186]
Please delete this client she was added incorrectly and later added

**Comment by carl-hamlin** [comment]
Please elaborate - this client also has two animals. What happened here?

**Comment by carl-hamlin** [comment]
Lenore, I need you to please elaborate on this issue.

**Comment by Lenorebarton** [comment]
The Client is Christine Sparks  not stark

**Comment by carl-hamlin** [comment]
This is taken care of.
