### ISSUE TITLE
Tech Edits for Animals

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#21]
I want to edit Birthdays!

**Comment by carl-hamlin** [comment]
Will fix intact field editting with full scale animal editting later in the month. Birth dates are not at this time slated for editability.

**Comment by lwilsonbooth** [comment]
Owner changed pets name..hope we'll be able to also.

**Comment by carl-hamlin** [comment]
commit 665404807d0d3a56de3f8bc88a07ca65a97b0349
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Jul 19 10:31:39 2019 -0700

    Enhancement 21:
    
    (UNTESTED COMMIT)
    
    This is a first swing at tech edits for animals, and it is being
    posted from a location with no internet. This commit is untested
    and should not be pushed to production as is.

**Comment by carl-hamlin** [comment]
commit 85022d42498ae6dc3d9e3f057f399c74ba78bd94
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Jul 19 21:04:04 2019 -0700

    Enhancement 21:
    
    Breeds are now working in the edit modal.

**Comment by carl-hamlin** [comment]
commit 71393417c44f5e45bf5a61809cb6da37dd816e11
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Sat Jul 20 09:58:29 2019 -0700

    Enhancement 21:
    
    The techs may now edit animals within a limited scope.

**Comment by carl-hamlin** [comment]
commit 3aa6097d5cbeb4caef23398abb49990553937d21 (HEAD -> enhancement.21, origin/enhancement.21)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Sat Jul 20 10:35:55 2019 -0700

    Enhancement 21:
    
    Aesthetics - Breeds now come up correctly in the edit modal. I
    think this motherfucker is ready to be released into the wild for
    banging upon.
