### ISSUE TITLE
Rabies Tag Search

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#219]
We need to be able to search for issued Rabies tags on clients. If a pet gets found, the rabies tag needs to be traced back to the vet so the animal can go back home.

**Comment by carl-hamlin** [comment]
Tentative list of steps:

- New table with running lot and tag numbers.
- Certificate overhaul - lose the floating modal and use values calculated from line item.
- Modify line item entry to drop rabies info at the animal level when a rabies shot is entered. (Heavy stupid here).
- Ensure charity rabies does not generate a tag.
- Move certificate generation to animal level, and only offer for animals current on rabies.

**Comment by Lenorebarton** [comment]
Amanda Myers, Jack  , 60284

**Comment by Lenorebarton** [comment]
Becky Maghy, Lily, 60285

**Comment by Lenorebarton** [comment]
Becky Maghy, Daisy

**Comment by Lenorebarton** [comment]
Becky Maghy  Daisy  ,  60283

**Comment by lwilsonbooth** [comment]
Brenda Yodice, Spirit, 60286

**Comment by lwilsonbooth** [comment]
Nadine Chandler, Midge, 60287

**Comment by lwilsonbooth** [comment]
Robyn Cross, Lucy, 60288

**Comment by Lenorebarton** [comment]
Marlene Wickum, Tippy, 60290

**Comment by Lenorebarton** [comment]
Paul Mertens, Emmy, 60289

**Comment by Lenorebarton** [comment]
Melanie Riley, Bella, 60291

**Comment by Lenorebarton** [comment]
Matt Millsap, Dally, 60292

**Comment by lwilsonbooth** [comment]
Christine Korelin, Wilson, 60293

**Comment by lwilsonbooth** [comment]
Heath Carlins, Chewy, 60294

**Comment by lwilsonbooth** [comment]
Linda Turner, Max, 60295

**Comment by carl-hamlin** [comment]
commit 9a4d291a64ca13af6c4104c2698bdd4b3784ec4e (HEAD -> e.219, origin/e.219)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Jun 23 12:56:17 2020 -0700

    Enhancement 219: Rabies Tag Search
    
    Underlying infrastrcutre is (hopefully) complete. Rabies tags work
    correctly and use the new data pool. Rabies vaccines contribute
    correctly to the pool. Next step, build the search interface.

**Comment by Lenorebarton** [comment]
Norman Adair, Dallas 60296

**Comment by carl-hamlin** [comment]
commit d1b480cb6bdcb527d53cf4523651f19afdbb5a7f (HEAD -> e.219, origin/e.219)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Jun 23 17:17:47 2020 -0700

    Enhancement 219: Rabies Tag Search
    
    This looks like it's ready for testing. Search is in, and so far
    I haven't been able to break it.

**Comment by lwilsonbooth** [comment]
Nathan Glow, Daisy, 60298

**Comment by lwilsonbooth** [comment]
Helen Dalton, Rouge, 60299

**Comment by carl-hamlin** [comment]
Next up: print button for rabies certificate.

**Comment by carl-hamlin** [comment]
commit f5755e99fda542bc1ef874e3cecc34110d0a40a3
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Jun 25 11:35:52 2020 -0700

    Enhancement 219: Rabies Tag Search
    
    Fixed issue with animals that only have a tag and no vaccine on
    record.

**Comment by carl-hamlin** [comment]
commit 52acaad9819add02308957d29a4630a12bbb030a (origin/e.219, e.219)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Jun 25 17:08:17 2020 -0700

    Enhancement 219: Rabies Tag Search
    
    Lot number and tag number were coming up for species other than
    dogs.
    
    Made line item interface species-aware. Problem solved.

**Comment by carl-hamlin** [comment]
Front desk reports no current issues. Closing issue.

**Comment by carl-hamlin** [comment]
Loren discovered that the search mechanism was occasionally producing duplicates. Re-opening ticket.

**Comment by carl-hamlin** [comment]
commit 43e13cbc3f8088914aca80adbc718ba1c0e3e814 (HEAD -> e.219)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 6 14:34:36 2020 -0700

    Enhancement 219: Rabies Tag Search
    
    Turns out that animals linked to more than one caretaker were
    showing up twice in the search.
    
    That's fixed now.
