### ISSUE TITLE
Multiple dates on one printable invoice.

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#227]
Often we have a client who orders a medication before an appointment but pays for both at the same time, and the Date issue, prescriptions are filled the same day of the appointment, but show the following date.  if when printing, we could choose the 2 dates with charges we could save paper and a little time.

**Comment by carl-hamlin** [comment]
Thank you for bringing this up - this issue should be resolved by issue #226's resolution.
