### ISSUE TITLE
Rabies Certificates

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#228]
If possible could the rabies certificates show if the animal is fixed or intact? Clients request it to be visible on the certificates they recieve. The Pound issues a larger fee for intact animals when liscencing them. Thank You.

**Comment by carl-hamlin** [comment]
commit b44f15c78477bbfaed6e8282c58c4fc2e05261fc (HEAD -> record.keeping, origin/record.keeping, origin/e.228, origin/HEAD, e.228)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Jul 2 14:27:48 2020 -0700

    Enhancement 228:
    
    Rabies certificates now indicate intact status.
