### ISSUE TITLE
Renee Caspro

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#231]
Client's name is Renee Castro  two accounts.  Izzy on Caspro account should be put on Castros accout.

**Comment by carl-hamlin** [comment]
Caretaker ID 2701 'Renee Caspro' has been removed from the database.
Her phone record has been removed from the database.
Her payments have been assigned to Caretaker ID 46 'Renee Castro'.
Animal 'Izzy' has been transferred to Caretaker ID 46 'Renee Castro'.
Animal 'Ezzie' has been removed from the database.
Closing issue.
