### ISSUE TITLE
Information On Pet Doesn't Appear

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#29]
Information on Pets won't show up after entered

**Comment by carl-hamlin** [comment]
commit d075a62a5f61aa23ea34e2b3a3e97f47a72242e3 (HEAD -> record.keeping, origin/record.keeping)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Apr 9 12:14:07 2019 -0700

    Record Keeping: Caretakers
    
    Fixed Bug #29 - Information on Pet Doesn't Appear:
    
    Well, mostly. When I fixed the problem with weight, color, and
    birthdate being erroneously editable from search, I failed to
    modify a tag that causes the information to bind properly on the
    page.
    
    That was *really* stupid, and has been fixed.
    
    While I was in there, Loren noted that the goddamned Intact,
    Caution and Deceased checkboxes aren't working, and after about an
    hour of fucking around with them, I've decided to post this fix to
    get the weight, birthdate and color back online, and fix the
    goddamned checkboxes in their own bug.

Closing issue.
