### ISSUE TITLE
Payment Not Processed

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#294]
Ellie Burns' account in BARKS is faulty. First it would not let me submit her as a new client. I got the black screen for over 20 minutes. Now it wont process her payment of $64.50 as a credit transaction. I did leave the page open in case it ever finishes loading.

It finally loaded at 4:31pm over an hour later..

**Comment by lwilsonbooth** [comment]
Now Kathrine Ramberg has a total on her account of 21.60 that was paid today. It wont go through though.

**Comment by carl-hamlin** [comment]
Looks like this is taken care of. Closing issue.
