### ISSUE TITLE
Add New Animal To Existing Client All Fucked Up

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#30]
Can't add new pets to existing client. It wigged out

**Comment by carl-hamlin** [comment]
I've spent about 45 minutes trying varied and sundry methods to get this issue to reproduce, and I just can't seem to make it snot work properly. I'm closing this bug out, and will re-open it if the issue crops up again.

@lwilsonbooth - If you can make this happen again, please feel free to re-open this bug yourself and give me details as to what you were doing when it happened. Thanks!
