### ISSUE TITLE
Barks Not Loading

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#32]
Takes too long to load after posting new client information

**Comment by carl-hamlin** [comment]
@lwilsonbooth - Thanks for posting. The length of time that it takes to post new client information has everything to do with the quality of the internet connection. There really isn't much I can do about shitty internet, unfortunately. The good news is that we're about to move to a new company for our internet and phones, which will hopefully improve our quality of life considerably, internet-wise.
