### ISSUE TITLE
Wrong Pet in Account

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#325]
Tammy West CID2436, Came in with their new cat Ike, When verifying their account I asked if the Feline in the account belonged to them, They said no. Would you please remove Ennie from their account?

**Comment by carl-hamlin** [comment]
FOCAS cat. As a matter of policy, we keep the deliverer of the animal on record as a point of contact for the animal, although in this case FOCAS is the primary caretaker.
