### ISSUE TITLE
Records Faxed

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#326]
Jim Glisson 925-726-8508, would like Doctors notes on Lional faxed to Nationwide insurance.
His Policy # C-2659492, fax # 714-989-5600

**Comment by carl-hamlin** [comment]
Teri, we do not fax records, but we will be happy to send them via email. I'll see if I can get an email address for Nationwide, and please, in the future, make sure you get the email address when someone wants records.

**Comment by carl-hamlin** [comment]
The requested records have been sent to Nationwide's record submission email: submitmyclaim@petinsurance.com.
