### ISSUE TITLE
Same Client, Different last name

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#329]
Would you mind combining Joanie Chinco (CID 2014) and Joann Anderson (CID 412)? They are the same client, She came in today with a new dog adn we discovereed she had two accounts with us. I have already linked Shea from the Anderson account to the Chinco account

**Comment by carl-hamlin** [comment]
Loren, I'm worried. As of 2:13pm on December 9th, Shea is *not* linked to the Chinco account, and I think you might have linked Shea to a different account inadvertently. I'll check.

**Comment by carl-hamlin** [comment]
Huh. No - the only other linkage there is to the Humane Society. Weird; looks like the link just never happened. I'll fix it now.

**Comment by carl-hamlin** [comment]
This is fixed.
