### ISSUE TITLE
Back End Visit Buttons

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#34]
Finalize, Line Item, and Annotation buttons should not be visible on front end.

**Comment by carl-hamlin** [comment]
commit dec4c57eef8f7ed3688ff86153dac01c29055914 (origin/caretakers, caretakers)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Apr 10 14:32:47 2019 -0700

    Record Keeping: Caretakers
    
    Fixed Bug #34 - Back End Visit Buttons:
    
    Finalize, Annotation, and Line Item buttons were being erroneously
    displayed to front desk staff. This has been corrected.

Closing issue.
