### ISSUE TITLE
Not Deleting phone space

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#341]
When a mistake is made adding or correcting a phone, if you hit the submit button, it deletes the phone space.   Could you please fix, so adding the correct number is  possible.  Thank you

**Comment by carl-hamlin** [comment]
This is fixed.

When posting issues to GitHub please include:

The caretaker you were working on when the issue occurred, including their CID.
The animal and AID as well, if an animal was involved.
Detailed description of what happened and what you were trying to do when it happened.
Pertinent data to fixing the issue, such as the telephone number you were attempting to enter when it did the big kablooie.

Thank you.
