### ISSUE TITLE
Same Client

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#342]
Terry Turner has an outstanding balance of $380.00 Under the pet Payton.
Stefanie Turner has a balance of $0 on the same pet Payton. Both caretakers share the same address.
The animals aren't linked.
I found while adding a new client

**Comment by carl-hamlin** [comment]
I'll bet this kind of problem is *rampant*.

Please, please, please check and make sure that the animals don't already exist before creating them.

I'll take care of this today or tomorrow.

**Comment by carl-hamlin** [comment]
This is fixed.
