### ISSUE TITLE
Can't Change Age / Sex

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#35]
When clients bring in FFP's we won't know their age or gender or coat color until they bring them in and the Technicians tell us. Makes it hard to put into Barks

**Comment by carl-hamlin** [comment]
@lwilsonbooth - Thank you for reporting this bug. With FFP animals, we'll be entering them into BARKS at time of arrival. As a general rule, you won't ever be able to go back and modify immutable fields such as age and gender after the fact, but in cases of improper entry that requires correction, those things may be reported directly to me, and I'll fix them on the back end.

Also - when you enter bugs, please take a look at the 'Related Issues' list that forms as you're typing the title of the bug. This bug, for example, duplicates an issue entered a couple of days ago. :)

Closing issue.
