### ISSUE TITLE
Email Vaccine Records

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#356]
Jackson Creek is requesting records for our client, Karen Maize, and her pets Bella and Romeo, Romeo is in BARKS but Bella is not. 
Their email address is Jacksoncreekvet@yahoo.com

**Comment by carl-hamlin** [comment]
Karen Maize is not our client. I let Jackson Creek know that she was not our client about two weeks ago. I think this issue is a duplicate, but if not, go ahead and re-open it with clarification.
