### ISSUE TITLE
Add Katherina Gower to BARKS

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#374]
Would you mind adding another phone number to Paige Gower's (2531) account?
The phone number belongs to her mother who has been paying for her pet Oliver.
Katherina's number is 2092899047

**Comment by carl-hamlin** [comment]
Loren, we need accounts in BARKS for everyone who is paying on an animal. When someone pays for a visit, the invoice for that visit should show their name and address on it.

The way we want to address this is not to add a number to Paige's account that doesn't belong to Paige, so much as to make an account for Katherina and link Oliver to Katherina, and run invoicing from Katherina's account. Please gather the requisite information and put that account together. I'll leave this issue open and monitor for closure. When the new account is in, please comment here to that effect.

**Comment by lwilsonbooth** [comment]
Will add the mother to BARKS when I get her info.

**Comment by carl-hamlin** [comment]
How's this coming along, Loren?

**Comment by lwilsonbooth** [comment]
I have added Kathrina Coggins to BARKS and linked "Oliver" Gower.
