### ISSUE TITLE
Payment Added Wrong

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#390]
I just posted $68.00 dollars as a credit when she paid Cash. Can you fix this? Client is Joann Valderama CID 1326. 
Also the pet is marked deceased. The owner didnt tell me that till after I took her payment. I told her we would need to she her alive pets before sending any new medications home. She complained about how Dr Black didnt do that.

**Comment by carl-hamlin** [comment]
Thank you for letting her know that. How did the payment type get screwed up?

**Comment by carl-hamlin** [comment]
Feexed
