### ISSUE TITLE
Payment Added Wrong again

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#391]
Lucy Garcia got posted as a cash payment as well. She paid $81.00 on her card not in cash. CID is 1822.

**Comment by carl-hamlin** [comment]
How did this happen?

**Comment by lwilsonbooth** [comment]
Not quite sure what exactly happened that was a crazy day. Most likely error on my part just posting it wrong.

**Comment by lwilsonbooth** [comment]
A lot of the time when a client will walk up I switch the option from cash to card and then change it back if they change their decision to pay with cash or credit or check. Not sure if maybe that is why it is being posted incorrectly or not.

**Comment by carl-hamlin** [comment]
Feexed
