### ISSUE TITLE
Client added wrong?

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#400]
Monica White(CID 2985) had brought in her dog Koda on the 16th of March this week and for some reason her dog was put onto Monica Wright's account. This is not her and she would like her pet removed. Also she is in the system already and I linked the pet to that account. But the account is under her maiden name. Is that a problem and does it need to be changed? Even if she will be changing her name legally back to Miller?
Monica Miller (CID 2617) is the correct account.

**Comment by carl-hamlin** [comment]
Loren.

When you add items like this to GitHub, please include the IDs for all parties concerned, caretaker and animal. Yes, I can usually look them up, but my time is expensive to the clinic, and should be used fixing problems rather than gathering info.

**Comment by carl-hamlin** [comment]
Fixed.
