### ISSUE TITLE
Animal linked to wrong account

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#402]
Karla Hill-Williams(CID 3277) came in today to inform us of her father, Jack Hill's passing. She gave me her information so she can continue bringing her father's dog to us. As I was adding her to the system, I went to link the animal to her account but couldn't locate the dog. After further inspection I found him linked to Carla Williams (CID 1378). Carla Williams does not have ownership of this animal nor has she ever brought him in to see us. Are you able to remove the linkage? Pet's name is Cooper (CID 4332)

**Comment by carl-hamlin** [comment]
Feexed
