### ISSUE TITLE
End Of Day Comes Up With Wrong Names

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#403]
Occasionally End Of Day will come up as someone else paying for a patient we've seen that day, but if you look up their account there is no payment or visit logged. I believe this is happening because when the payment is posted, I have already typed in a new name to search afterwards. Because of these incidents I have stopped typing in new searches before posting payments.

**Comment by carl-hamlin** [comment]
Tried the suggested method for reproduction. Does not look like a good candidate for a cause. Thanks for the idea, though.

**Comment by lwilsonbooth** [comment]
This Happeed Again. Once again the only thing I did was type another clients name into the search engine before hitting search and went back to post the payment.

**Comment by carl-hamlin** [comment]
This appears to have been resolved at some point between posting and today's date, which is not surprising; the entire system whereby caretakers are represented has been overhauled.
