### ISSUE TITLE
Pet Added Twice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#408]
So I screwed up just now, when the client came up to the window to pay for one of her pets, The animal wasn't in her account, so I added her. Took the payment and realized she was paying with someone else's card. When looking up the name on the card I found that we had already seen the pet and is now in our system twice.
The Owner the payment was added to was Dan Burrow 1701.
The Correct owner of the dog is Cynthia Moreland 3236.
Kiana  7651. Correct Spelling.
Keona 7730. Added today. This pet does have a visit from today but it needs to go onto the correct pet.

**Comment by carl-hamlin** [comment]
Feexed
