### ISSUE TITLE
Can't Add Pet To Existing Client

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#41]
Won't submit new pet. Had to reload page to get pet submitted.

**Comment by carl-hamlin** [comment]
@lwilsonbooth - Please give me a little more detail. It sounds like all that happened here was that you had to reload the page and then it worked. Was it a connection issue, or was there more to it?

**Comment by carl-hamlin** [comment]
Haven't heard back on this one in quite a while Closing until more info comes through.
