### ISSUE TITLE
Wrong Medication

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#414]
Our Client Kathleen Madsen (CID 2476) stopped in today to pick up Bravecto for her three dogs. While adding them to her account I added one that was the the wrong size, Thankfully all the Bravecto items we have are the same price. Would you mind fixing the Bravecto in Callie (CID 6099) Visit ID 15738. Her correct size is 44-88# and the one I put in was 22-44#

**Comment by carl-hamlin** [comment]
Feexed
