### ISSUE TITLE
Doubled Client

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#417]
OK. I am finally starting to see why the crappy internet connection makes you all crazy. I have once again added a client to BARKS after searching first, finding nothing, and now we have Crystal Nichols in the system twice. CID 3335 Needs to be deleted. The correct account is CID 3272. Also when searching Snubbull's other owner to link him, BARKS continuously was telling me it could not find Jacob Horch CID 3271. But I believe that was the internet malfunctioning.

**Comment by carl-hamlin** [comment]
Thank you, Loren. This has been fixed.

For future reference, the list of caretakers is re-loaded every time you push the 'Search Humans' button.
