### ISSUE TITLE
Smoke Medication Refill Visit

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#423]
I clicked the refill button (VID 15920) for Shirly Nester (CID 3032) and her pet Hank (AID 7190) this morning when I had called the client back to confirm she was picking up today. When she was paying I noticed that her bill was for $120.00 and not $60.00 like usual. Upon further investigation, I found that Dr. Simko had added her new Prescription with the correct dosage on the visit. Would you mind deleting the visit I had made? I took the payment on the correct visit (VID 15928).

**Comment by carl-hamlin** [comment]
Fixed. Great job putting this entry together, Loren.
