### ISSUE TITLE
2 clients Same dog

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#426]
Corwin Haynes (cid 2470) and Ester Leriget (cid 1321) are co-owners of Cheyanne (aid 6092) and Peppa Dew (aid 3599). Corwin Haynes has a "Peppa Dew" (aid 6232) in his account but it is not the same as the dog in his wife's account. Would you mind deleting the duplicate pet with  AID 6232?

**Comment by carl-hamlin** [comment]
How did this happen?

**Comment by carl-hamlin** [comment]
Fixed
