### ISSUE TITLE
Smoke Visit

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#428]
Marina Casey (CID 2276) stopped in today to pick up more Lactated Ringers, an IV set up, and 20 syringe needles for her cat, Sunny(AID 5657).
She had originally wanted to pick up Bravecto for her dog, Ivan (AID 5658) and a paper RX for heartworm since she was in the process of moving. We had researched what preventatives had both the Heartworm and Flea and Tick in them. After I had Dr. Simko fill out a slip for the client  and we were settling the bill she decided she didn't want to purchase the Bravecto. So would you mind removing the visit for today with the VID 16105.

**Comment by carl-hamlin** [comment]
Fixed
