### ISSUE TITLE
Forgot To Post Transaction

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#429]
April 23rd (VID 16178 and 16181)Joy Chun (CID 3183) paid for her visit with Zeus (AID 7543) and it was not posted. Do you want me to post now or do you need to fix it through the back door? Her bill was for $140.00 and she paid with a Credit card in full. The payment is in the Clover machine but was not posted in barks.

**Comment by carl-hamlin** [comment]
Fixed. This sort of thing isn't supposed to be happening anymore now that you're verifying with end of day.
