### ISSUE TITLE
Email Records And Correct spelling

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#430]
Could you please email records: Client ID# 2859 Mark Sites, Pets  ID# 6833 Mae and ID #6833 Samson to:
michellesanchez@farmerinsurance.com.  Client's cell 209-843-3036, Mr Sipes requested this email.
Correct spelling of last name is Sipes.

**Comment by carl-hamlin** [comment]
Loren, did you send these out?

**Comment by lwilsonbooth** [comment]
Should I wait till you fix his name or send it now?

**Comment by lwilsonbooth** [comment]
Done.

**Comment by carl-hamlin** [comment]
Fixed
