### ISSUE TITLE
Add Food To BARKS?

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#432]
Hills Science Diet Feline C/D Ocean Fish 5.5oz cans are not in BARKS - when clients by this food we have just been putting it under the C/D Chicken. The Hills Science Diet Feline C/D Vegetable, Tuna, And Rice Stew 2.9oz cans are not in the system either.

**Comment by carl-hamlin** [comment]
Please check with Dr. Simko and make sure she meant to order the abberant foods. She usually lets me know when something new comes into the clinic so I can put it into BARKS.

**Comment by lwilsonbooth** [comment]
She said might be a good idea. It will make clients happy. Prices might be different so we should research it.

**Comment by carl-hamlin** [comment]
Fixed
