### ISSUE TITLE
Un-posted Transaction

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#436]
I have found yet another transaction I hadn't posted from April 27th. Emily Stoller CID 1167 has a total of $111.00 that according to the clover machine she did pay for. I am starting to see a pattern, If i take the machine outside to take the payment, it doesn't always make it into BARKS. So from now on, I will not be taking it out to the client. And if I do, then i will be double checking that it gets posted.

**Comment by carl-hamlin** [comment]
Loren, the thing I genuinely don't understand here is how this gets past your nightly screen using the end of day. If you're comparing each transaction on the envelope to the end of day manifest, then there's no way a missed posting should go unnoticed unless you're just skimming through it.

Please take the end of day screening more seriously. Thank you for catching this one, and picking up on the fact that you're skipping the posting to BARKS when you take the machine outside; I appreciate your willingness to analyze the situation for cause; that's a level of initiative that increases your value to the company.

**Comment by carl-hamlin** [comment]
Additionsally, when we're talking about payments, please post the visit ID associated with the abberant payment. I can look it up, but it's a faster fix if I don't have to.

**Comment by carl-hamlin** [comment]
Fixed
