### ISSUE TITLE
Client Entered Twice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#441]
Margarito De Haro CID 3398 is the same person as Margarito DeHaro CID 939.

**Comment by carl-hamlin** [comment]
How did this happen?

**Comment by lwilsonbooth** [comment]
Not Sure I searched him before adding the new account, but found no results. The client was unsure if he had been seen by us or not.

**Comment by carl-hamlin** [comment]
Feexed
