### ISSUE TITLE
Clients Records Pick up    Request

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#444]
Ann Anderson ID#0397. Would like to pickup records for her pets:  Oso ID#1425, Kali ID#1424 and Oskar ID#1423.
She's moving out of the area.  Please call her when ready for pick up 209-418-5436.  Thank you

**Comment by carl-hamlin** [comment]
So.... you checked with Dr. Simko, then got her records together for pick-up, right?

**Comment by lwilsonbooth** [comment]
This Is Done.
