### ISSUE TITLE
End Of Day Wrong

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#454]
Bonnie Marshall paid with two checks on June 3rd. VID 17204 and 170206. The first payment was check # 3829 with $318.00 and the second one was check # 3830 with the remaining $35.00. She had to pay twice because Barks Hadn't loaded the additional fees Dr put in.. (The Medicine). Barks is showing that she had paid $333.00 with that first check, But what is weird is the total still came out to $353.00. I have tried refreshing the page by holding down CTRL + F5 and clearing the Cache, Still it remains at a payment of $333.00.

**Comment by carl-hamlin** [comment]
Feexed
