### ISSUE TITLE
Change Appointment Details, Time, Reason, Date

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#46]
maybe we can do this, but i don't know how...change data after entering appointment time, reason etc.

**Comment by carl-hamlin** [comment]
Coming soon to a record keeping system near you.

When you post bugs, please assign me, and choose a label - 'bug' for something that's in the system but not working the way you expect it to, or 'enhancement' for something you think should be in the system but isn't. This would be an 'enhancement'.

**Comment by CMaxeyRVT** [comment]
If I may add a suggestion to this, 
With appointment scheduling there should be a slot that includes initials of the employee that made the appointment> that way if we need to follow up for training purposes or have questions we know who to talk to. I also feel that the appoitnment book should also show when the appointment was booked.

**Comment by carl-hamlin** [comment]
Fixed in Enhancement 77.
