### ISSUE TITLE
Emailing Records

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#463]
When emailing records yesterday, I had noticed that the Bloodwork doesn't show up on the preview I do before sending an email. Not sure if this needs to be addressed or not, But when emailing other vets, they might need those results as well?

**Comment by carl-hamlin** [comment]
Yes; I've shown you how to retrieve the bloodwork as well. I'll go over this with you again on Monday when I come in. Leaving open until then.
