### ISSUE TITLE
Rabies Malfunction 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#469]
Jane Gragg 3541 brought in her pets Bella 5062 and Buster 5061 to get their shots updated. When trying to bill them out and print the Rabies certificate, I found that Bella had no tag button to click and when clicking Buster's tag it said his Rabies number was 1. Not sure what happened but the Owner will need her certificates soon. 
Bella's Tag number should be 31249. Buster's Tag number should be 31250

**Comment by carl-hamlin** [comment]
I'll need the lot numbers for the vaccines to fix this one.

**Comment by carl-hamlin** [comment]
Fixed
