### ISSUE TITLE
Lists in Annotations for Treatments and PE

### ISSUE THREAD

**Issue by fractious16** [carl-hamlin/barks#47]
lists are  easier to read when complex exams or treatment protocols are recorded:
1 physical exam template that is preformatted as a list of systems.
2 Nurses orders for treatments should be numbered list in bullet format that they can check off as they are completed.
3 Details pending

**Comment by carl-hamlin** [comment]
commit 6d4aec4dec7e65b5f251a418c7f54b80f4e42407 (HEAD -> enhancement.47, origin/enhancement.47)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Sun Oct 13 12:19:29 2019 -0700

    Enhancement 47:
    
    It is no longer possible for annotations to be dependently
    authored. All annotations now go in under the name of the entering
    user.

**Comment by carl-hamlin** [comment]
commit 5b6dace557fe70a032bc8f62bb1a399f1c67160c (HEAD -> enhancement.47, origin/enhancement.47)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Sun Oct 13 15:00:55 2019 -0700

    Enhancement 47:
    
    Removed Rx persuant to discovery of necessity for e.113.

**Comment by carl-hamlin** [comment]
commit 49b090a270c679db0e8c7a39c238ab436e52aa12 (HEAD -> enhancement.47, origin/enhancement.47)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Sun Oct 13 16:57:17 2019 -0700

    Enhancement 47:
    
    First pass at templated exams.

**Comment by carl-hamlin** [comment]
Turns out my understanding of what Dr. Simko wanted was lacking in a couple of key areas, so we're going to take a second swing.

**Comment by carl-hamlin** [comment]
commit 53cfc704e103323ea31584178480633a05e1b772 (HEAD -> enhancement.47, origin/enhancement.47)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Oct 15 10:02:52 2019 -0700

    Enhancement 47:
    
    Second pass at templated exams.

**Comment by carl-hamlin** [comment]
commit c151c0e292f29e52062c0818dac13825d67c6134 (e.47)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Oct 16 13:42:04 2019 -0700

    Enhancement 47:
    
    Dr. Simko asked for a few minor changes to the exam template.

**Comment by carl-hamlin** [comment]
Closing issue - looks like we're done here.
