### ISSUE TITLE
Yet another Outstanding Balance

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#470]
Michelle Dickey once again has a balance on her account she claims to have paid in full on that day, CID is 1683 AID is 8062 VID is 17294.
The remaining balance is $36.00

**Comment by carl-hamlin** [comment]
Wow. This visit is like a textbook example of how *not* to use BARKS. I'll go over it with you guys on Monday when I come in. Leaving open for the moment.

**Comment by carl-hamlin** [comment]
Went over it with Dr. Simko and apparently we need a mechanism to codify one-time kitten visits in BARKS, and until then, we're going to continue to pollute the data stream in this fashion.

In other news, I've fixed the balance issue.
