### ISSUE TITLE
Payment Void

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#471]
Emily Stoller 1167 came in today to pick up Cagey's 6377 medicine VID 17848. She paid $20.00 on her credit card. The Clover machine took it offline and by the time she left it had come back online and declined the payment. I had already posted it as paid because the machine said it was paid before it came back online. I let the Owner know that the payment did not go through and she would have the $20 balance on her account and would need to come in to pay it. Emily Stoller came in the next day and paid with a $20.00 dollar bill. Dr. Simko has it.

**Comment by carl-hamlin** [comment]
Feexed
