### ISSUE TITLE
Remove Items From Invoice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#472]
Owner Linda Taylor left a message saying she needed 1 box for each dog of Triheart and said she'd pick them up in the morning. Her husband stopped by and only wanted two of the boxes. Would you mind removing the other two from their account? CID is 1615 and VID is 17939 and 17938. AID is 4176 for Oaty and 4177 for Lady.

Owner came back to switch the Triheart 25-50# for the Triheart 0-25# since the animals are smaller.  We owe them $8.00 i have now way of refunding. Told Owner we would refund or send a check- Dr told me to say this.

**Comment by carl-hamlin** [comment]
The visits have been removed. You should be able to remove visits that you created up until they have payments on them. Let's look at this on Monday. I'll issue a refund check on Monday as well. Leaving open for the moment.

**Comment by carl-hamlin** [comment]
The check is in the mail. Closing issue.
