### ISSUE TITLE
2 Clients, Same Dog

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#476]
Phyllis Wright CID 2303 and Jerry Haynes CID 2895 co-own pet Annie. Annie is is the system twice. One under Wright as AID 5719 with Visits 6568,11429, and 12154. The other Annie that is under Haynes is AID 6913 with VID 11416. This is the same dog on both client records. Please Fix if possible.

**Comment by carl-hamlin** [comment]
Why does this keep happening?

**Comment by carl-hamlin** [comment]
This is fixed.
