### ISSUE TITLE
Rx's Returned to Inventory

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#483]
Meds never picked up; returning to Inventory; please remove item from client acct.'s

Kevin Watchman CID 2491    Boos AID 6976    Carprofen 75 mg. #30  VID 17534  on 6/16/21
Virginiaa Torres  CID 2495     Jill  AID 6125     Acepromazine 10mg #5  VID 16852 on 5/20/21
Michael Reyna   CID846        Sebastian  AID 6823    Amoxicillin 500mg #30  VID 15748  on 4/7/21
Michael Reyna   CID846        Shadow  AID 2734     Prednisone 20mg #20  VID 15749 on 4/7/21
Kerry Smith  CID 3106           Beanie  AID 7361     Carprofen 100mg #30   VID 16161 on 4/22/21

**Comment by carl-hamlin** [comment]
Animal ID 6976 (Boos) does not have a visit involving Carprofen 75mg. No action taken.

**Comment by carl-hamlin** [comment]
Animal ID 6125 (Jill) does not have a visit involving Acepromazine 10mg. No action taken.

**Comment by carl-hamlin** [comment]
Animal ID 6823 (Sebastian) does not have a visit involving Amoxicillin 500mg. No action taken.
Animal ID 2734 (Shadow) does not have a visit involving Prednisone 2omg. No action taken.

**Comment by carl-hamlin** [comment]
Animal ID 7361 (Beanie) does not have a visit involving Carprofen 100mg. No action taken.

**Comment by carl-hamlin** [comment]
None of the listed animals had visits associated with these prescriptions. Moving forward, before you ask me to research and remove visits, please ensure that they actually exist. Closing issue.
