### ISSUE TITLE
Deceased Pets

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#497]
It would be EXTREMELY helpful (and less awkward) if, in BARKS, Deceased Pets could show up in a different color, or with a (D) after the name (on the list of pet names).
Please let me know if you have any questions. Thank you.  Julia

**Comment by carl-hamlin** [comment]
commit 1bcfb840b4ac2209979ab0687384b9ed562101b4 (HEAD -> record.keeping, origin/record.keeping, origin/e.497, origin/HEAD, e.497)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Aug 12 11:52:29 2021 -0700

    Enhancement 497: Deceased and Species Markers in List
    
    Animal listing now includes gender, species, and deceased
    indicators prior to record activation.
