### ISSUE TITLE
Invoices and Payments

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#501]
Payments made do not currently show up on Invoices.  There is currently a line item called "Less Payments" which always shows $0; Can this line show the amount of the payment(s) made?  It would be more clear to the client and front end staff.

Example A:    Payment made by single method.

                       1    Feline C/D 4# bag     Neves     $25.00                
                       1    Rabies Vaccine           Neves     $15.00
                                                    Visit Total:          $40.00
                                                 **Less Payments:  $40,00**
                                               Total Balance Due:  $0.00

Example B:   Payment made by multiple methods (ie Part Cash; Part Credit)

                      1    Feline C/D 4# bag     Neves     $25.00                
                      1    Rabies Vaccine           Neves     $15.00
                                                   Visit Total:          $40.00
                                                **Less Payments:  $10.00
                                                                             $30.00**
                                              Total Balance Due:  $0.00

Please let me know if you need more clarification.  Thanks so much. Julia

**Comment by carl-hamlin** [comment]
Julia, I think there's been a slight misunderstanding - 'Total Balance Due' is the total that is owed by the client. 'Less Payments' is the total owed on the particular visit. Some invoice calculations result in multiple visits on the same invoice, and Total Balance Due only appears on the bottom.

That having been said, I take your meaning to be that you'd like to see some indicator of payments registered against visit balances on the invoice, and will get that working within the next few days. Please let me know if I've misunderstood your request.

**Comment by julsneves** [comment]
Ok...I did not take into account that multiple animals may be seen on same visit.  

Yes.  You do understand correctly.  That is what we would like to see.  (However, if possible, we would also like to see each payment (if using multiple payment methods on the invoice).  Does that make sense?

**Comment by carl-hamlin** [comment]
Yep.

**Comment by carl-hamlin** [comment]
commit c6bc74a087342848d24ed232b95157384d038f19 (HEAD -> record.keeping, origin/record.keeping, origin/b.501, origin/HEAD, b.501)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Aug 18 15:06:51 2021 -0700

    Bug 501: Payments Don't Show on Invoices
    
    Now they do.
