### ISSUE TITLE
Age Field in Animal Profiles

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#502]
Under Animal Info:  Can we please add a box called "AGE"  (which would auto populate from the "BIRTHDATE" field?
(Perhaps this could be placed between Weight and Birthdate)

Also: can we please find a way (drop down, check box, etc) where we can indicate if BIRTHDATE is "Actual" or "Estimated"?

Thank you!

**Comment by carl-hamlin** [comment]
These are two separate requests. I'll set them up that way.

**Comment by julsneves** [comment]
Got it.  Thank you.

**Comment by carl-hamlin** [comment]
commit f5420b9e7e84e6558a03046ad65fa86ac4389e72 (origin/e.502, e.502)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Aug 19 16:02:59 2021 -0700

    Enhancement 502: Age Field in Animal Profiles
    
    There is now an age field in animal profiles.
