### ISSUE TITLE
Client Entered Twice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#504]
Deborah Olquin CID 2647 and Debra Olguin CID 2742 are the same client. Same pets and addresses match in both accounts.
Ms Olquin has Maya AID 6419 and Starla AID 8396. Ms Olguin has Blue AID 6606 and Starla AID 8396. Do you want me to link the other animal to the correct account. She will be in tomorrow and I will be asking her the correct spelling on her name and which pets belong to her.

**Comment by carl-hamlin** [comment]
Yes, please. I'll watch this space for the CID to remove. Thanks for catching this.

**Comment by lwilsonbooth** [comment]
Finally got a call from the client, Correct spelling is Debra Olguin.

**Comment by lwilsonbooth** [comment]
I had re-opened this Issue because Julia had been talking with the client and there was still an issue with the name. I re-opened it so she could add to the existing issue. I believe this issue has finally been resolved.
