### ISSUE TITLE
Birthday Missing!

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#521]
So I added Rachelle Hillsinger CID 3692 and her dog Daisy AID 8467 today, but I wrote the birthday wrong. I meant to put 11-30-2019 and instead put 2021 as the year. So I went to fix it and now there isn't a birthday, like the whole spot where the birthday is, Is missing. Just a blank space.
Also happened to Jane Gragg CID 3541 and cat KoKo AID 8420 when I went to mark him deceased.

**Comment by carl-hamlin** [comment]
Birthdate editing is operating as intended. If you get a birthdate from a client that is not a 'estimated' birthdate, then there should be no reason to alter it later. Please be careful entering birthdates.

I'll fix Daisy.

**Comment by carl-hamlin** [comment]
Fixed
