### ISSUE TITLE
Duplicate Entry  Scott Lewis

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#523]
There was a lag in processing (thought it was me) so entered same item twice.  Bill s/b for $75.00 (this is what I charged the card for.)
CID 2481
AID 7358
VID 19418

Thank you!

**Comment by carl-hamlin** [comment]
Thank you. This is fixed.

You should be able to remove line items you entered right up to the point at which the visit is finalized. If you're not sure how to do that, I'll show you on Thursday.

**Comment by julsneves** [comment]
Thank you, Carl.  I do know how...I was trying to get it to show up so I
finalized it.  I was not patient enough with our Internet today.   Grrr!
