### ISSUE TITLE
Smoke Visit VID: 20772 Denise Orr CID: 1529

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#590]
Carl, Please smoke VID: 20772 on CID: 1529, from 10/29/21
I refilled the PROIN 75 (before realizing we were out of stock); we were supposed to get in in the following week, so I left the $100.00 balance on her account.  However, she never picked up and another client needed it, so we sold to that client.
She never received RX; so she does NOT owe the $100.00.

Thanks so much.

**Comment by carl-hamlin** [comment]
Please, please, please, please, PLEASE, PLEASE, PLEASE, PLEASE, PLEASE for **fuck's sake**... **STOP PUTTING THE GODDAMNED PRESCRIPTIONS IN UNTIL YOU SEE THE WHITES OF THEIR EYES**.

Thank you.
