### ISSUE TITLE
Invoice Interface Error

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#591]
When changing or adding information to an existing pet, the invoice interface pops up. This has been happening for the last 2 weeks. Started a little bit after you had fixed the system to turn black when finalizing.

**Comment by carl-hamlin** [comment]
commit a6798e3cab2bf588ba1759aaeba6cfba7f2af884 (origin/b.591, b.591)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Nov 15 15:43:40 2021 -0800

    Bug 591: Invoice Interface Issue
    
    Turns out this was the result of a merge error a couple of weeks
    ago. Good catch, Loren.
