### ISSUE TITLE
Correct Client's last name  CID #2776

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#596]
Please correct spelling of last name from Woodruff to "Woodrumm"
Thank you.

**Comment by carl-hamlin** [comment]
Fixed.

Please, please, please, please, PLEASE stop writing caretaker info down and getting them into BARKS later on. Put them in WHILE YOU HAVE THEM ON THE PHONE. That way, you can ask them for the correct spelling of their name as you're entering it.
