### ISSUE TITLE
Correct Balance to $0   CID 0062

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#597]
Pam Derosiers CID 0062
This was a client that had balance in written chart, but Zero Bal in Barks; so you added balance into BARKS
Terri has confirmed that this balance was, in fact, paid in full, by client - but since they were told not to use paper anymore; the balance never got adjusted in paper file.
Bottom line; client balance is Zero.  (I can explain more if necessary.  Looking at balances and payments; this makes sense.)
Thank you,
Julia

**Comment by carl-hamlin** [comment]
Thank you for catching that.

Payments of any kind should be posted in BARKS, please.
