### ISSUE TITLE
Pet under Wrong Client

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#599]
Not sure how this happened, Jinjer Carter (CID 2413) has an appointment for today with her new puppy Copper (AID 8836)
Copper was put under Joyce Carter (CID 1864) I have already linked Copper to Jinjer Carter's account, could you please remove him from Joyce Carter's account

**Comment by carl-hamlin** [comment]
Looks like Julia put Copper in originally. Everyone, please be careful to ensure that animals are going in under the correct caretaker. This is fixed.
