### ISSUE TITLE
Printable Estimates

### ISSUE THREAD

**Issue by carl-hamlin** [carl-hamlin/barks#6]
At the moment, there is no way to print an estimate for customers to sign. This is a problem, in that customers have no real way to know what sort of financial hardship they'll be incurring as a result of our services. We expect that signed invoices will cut down on the number of folk who discover after treatment that they cannot pay. This is a piece of mission critical infrastructure that needs to be in place for MVP.

**Comment by fractious16** [comment]
Please have signed estimate scanned and inserted into visit.

**Comment by carl-hamlin** [comment]
Accidentally closed during tutorial.

**Comment by carl-hamlin** [comment]
commit b29f471ce144ad9bc286a73520d080b8d273def6 (HEAD -> enhancement.6, origin/enhancement.6)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Feb 20 17:10:31 2020 -0800

    Enhancement 6:
    
    First pass at printable estimates. The main code is in, but it
    still doesn't clean up after itself. Additional concerns with
    regards to quantification and potential issues with invisible
    pharmacy fees.
    
    Committing for portability and evaluation. Further commits are
    expected concerning this issue. Do not close.

**Comment by carl-hamlin** [comment]
commit 495bd5c9450fa5168a05fd80dfdcbace12a9ca57 (HEAD -> record.keeping, origin/record.keeping, origin/enhancement.6, enhancement.6)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Feb 21 15:08:20 2020 -0800

    Enhancement 6:
    
    Quantification issues have been addressed, hopefully, and the
    system now cleans up after itself. Fingers crossed, we're done
    with this for now. It's not pretty but it seems to work.

**Comment by carl-hamlin** [comment]
Dr. Simko has requested that completed estimates be able to be placed into permanent residency in client charts.

**Comment by carl-hamlin** [comment]
Progress on saved estimates will be tracked on Issue #235

**Comment by carl-hamlin** [comment]
Dr. Simko needs to be able to remove items from estimates while producing them without having to start over.

**Comment by carl-hamlin** [comment]
Items may now be removed from estimates. Fixed by commit 0b4ee216bab5b13d9b5c1b2d80dcea9af4739b7c. All referenced issues resolved - closing issue.
