### ISSUE TITLE
Pet Re-homed

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#600]
Susan Tomasich CID 2795 originally brought in George AID 8695 and Jane Doe Tomasich AID 8696 for their vaccines and they were re-homed to Jennifer Whaley CID 3133.
The client did not tell me that this pet was seen before by us until I had to go ask her if she wanted vaccines done. She then let me know that the kitten by the name of Niko AID 8843 had been seen under a different client .
So when you get the chance please add Jane Doe Tomasich's visits to Niko.

**Comment by carl-hamlin** [comment]
Fixed
