### ISSUE TITLE
Clients Occasionally Posting Twice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#612]
I just added a new client to barks and they got posted twice.
Elias Bedolla CID 3889 and 3890 are the same person and 3890 needs to be removed.
I searched the client first before adding new, hit submit and it was taking a little longer then normal when I got the notification that the client had been posted, I clicked okay and got another one.

**Comment by carl-hamlin** [comment]
This issue seems to have gone away on it's own. Yay for serendipity.
