### ISSUE TITLE
Submit Button on Pet Additions and Edits Needs Conditional Availability

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#615]
BARKS refused to post my visit for Penelope 8645 under Katherline Csabi 3778 
I got an error message saying that I forgot to add the coat pattern.
Fixed the coat pattern and tried again and the visit posted.
This is the first time this has happened to me.
EDIT: so I just did that again but it was a pet from Dr Black's time so all the info on the pet is incorrect and it went through just fine.

**Comment by carl-hamlin** [comment]
commit 9645336eac1fd7856ce141df21ee442e458da00f (HEAD -> record.keeping, origin/record.keeping, origin/b.615, origin/HEAD, b.615)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Dec 15 11:48:09 2021 -0800

    Bug 615: Submit Button for Edit Animals Must be Conditional Upon Field Entry
    
    Submit button for editting animals is now conditional upon field
    entries. It is no longer possible to submit edits with empty
    fields.
