### ISSUE TITLE
New Dog Breed

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#620]
8942 Max 
Dog needs to be changed to a Wheaten Terrier.

**Comment by carl-hamlin** [comment]
OK, so change him to a Wheaten Terrier, please. Or a Terrier Mix, if Wheaten Terrier isn't in the list.

Once you've done that, go ahead and close this issue.

**Comment by lwilsonbooth** [comment]
There is no Wheaten Terrier. That's why I made this issue. I wasn't sure if you needed all the different types of terriers in the system since there are so many.
