### ISSUE TITLE
Client and Animal Name Corrections

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#621]
CID #1357:  Jeannie Gollen  CORRECT Spelling is:  Jennie Gollon
AID #8852: Little Miss CORRECT to: Little Missy LouLou

**Comment by carl-hamlin** [comment]
'Little Miss' wasn't enough for these people? They absolutely *must* have the 'LouLou' bit on their invoice, or they're going to throw a fit?

Who the hell *are* these people and how did they survive to adulthood?

This is resolved.

**Comment by julsneves** [comment]
Right????!!
