### ISSUE TITLE
DHLPP Not Generating Reminder Tokens

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#645]
Mary Anne AID 3728, belonging to Carla Williams CID 1378, had a DHLPP on 4/13/20; but it does not appear on the list at top with Dogs reminders.  
Also, o got a reminder that her dog was due for shots now; so she scheduled an appt.  (There are NO shots currently due??)

Can you add the reminder  for DHLPP Due 04/13/23?  Thank you.

**Comment by carl-hamlin** [comment]
commit 38826f1570a090e630d8ee9e27d39c5fdc31a123 (HEAD -> record.keeping, origin/record.keeping, origin/b.645, origin/HEAD, b.645)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Jan 26 10:30:29 2022 -0800

    Bug 645: DHLPP Does Not Generate Reminder Token
    
    Now it does.
    
    Incidentally, Rattlesnake no longer does, per Dr. Simko's request.

**Comment by julsneves** [comment]
Ok...thank you for the info...did not know about RS.
