### ISSUE TITLE
Clarification on Euthanasia Cremation vs. Aftercare

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#668]
Carl, we are having lots of confusion re above.  There are 5 options currently in BARKS:
        Euthanasia                    The cost for the actual shot
        **Disposal Fee                 No idea when we use this.**
        Private Cremation         This one is obvious...
        Group Cremation          This one is obvious...
        **Euthanasia Aftercare     This one is confusing**

I believe PRIVATE and GROUP CREMATIONS should be taking place of Disposal Fee & Euth Aftercare.
If this is correct...can we eliminate these two from the system?  It wouldn't matter much but pricing is different.
Let us know.  Thank you   Julia/Loren

**Comment by carl-hamlin** [comment]
I concur, mostly. Some of those are in there from when we first transitioned to BARKS and had a lead tech who had a hand in the naming convention. Dr. Simko and I really need to sit down and standardize this. I'll arrange to do that with her in the near future.

**Comment by julsneves** [comment]
Thank you!

**Comment by carl-hamlin** [comment]
So, yes. Disposal Fee and Euthanasia Aftercare are completely redundant, and have been removed from the system.

As it stands now, we have the Euthanasia procedure, which Dr. Simko enters, and then 4 sizes of Private Cremation, 2 sizes of Group.

We'll see how well that works over the next few months.

**Comment by julsneves** [comment]
Thank you for this Carl!
