### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#674]
Please delete ID 4054 Duplicate.  I pushed the enter button, when nothing happened , I pushed it again.  Thank you.

**Comment by carl-hamlin** [comment]
Teri, you're going to have to tell me what that ID refers to before I can act on this request.

**Comment by tlutzi** [comment]
New Client Joey McClure entered twice, ID 4054 should be deleted.  Thank
you again.

**Comment by carl-hamlin** [comment]
Fixed
