### ISSUE TITLE
Delete additional Client

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#685]
When adding Abe Bradt a new client to barks, I pushed  the submit button, Denise Bradt came up twice with similarities, no relation. 
Next I push the submit button for new client Abe Bradt ID 4099, It came up to submit again.  So Abe Bradt is in twice.
ID 4099 and ID 4100.  Please delete ID 4100.  Thank you.

**Comment by carl-hamlin** [comment]
Fixed
