### ISSUE TITLE
Duplicate Client Found

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#692]
Please delete CID 2532  for Candace Wallace.  
Her correct CID is 2109

**Comment by carl-hamlin** [comment]
How did this happen?

**Comment by lwilsonbooth** [comment]
No clue, I am just browsing BARKS as the day goes, I just happened to have found these github fixes and upload them as soon as i can. I noticed that there was no phone number or animals under the account CID 2532.

**Comment by carl-hamlin** [comment]
Fixed
