### ISSUE TITLE
Smoke Pet

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#696]
Remove Kali AID 9428.
Caretaker is William Wiley CID 1475.
Pet is not real. Cat's name is Hayle not Kali.

**Comment by carl-hamlin** [comment]
Loren, when you say 'Pet is not real', I'm not sure what you mean. Please elaborate at your leisure.

**Comment by lwilsonbooth** [comment]
What I mean is there is no existing pet with that name in this client's household. When making appointments, you are unable to hear the clients clearly and they apparently cannot hear us either. There are far too many name changes the girls and I have to add for you to fix and it is mostly due to client's not speaking clearly or the phones being too static-y. They say yes the name is correct and then after paying their bill, they will complain that we spelled either the pet or their own name wrong.

**Comment by carl-hamlin** [comment]
Gotcha. Thank you!

**Comment by carl-hamlin** [comment]
AID 9428 had a euthanasia on record. Removed existing 'Hayle' and renamed 9428.
