### ISSUE TITLE
Vax Due Date  Incorrect  CID 1288

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#705]
Perhaps this issue already resolved; but this client needed proof of vaccines for AID 3544
At top of chart it shows DHLPP DUE 2019-08-05  Records show we GAVE the vaccine on that date.  However after the DHLPP is shows the words Single Dose vs 1 yr or 3 yr  could that be the reason?
I hand altered the information on printed record and initialed for her.
Please let me know what is up with this one when you get a chance.  Thank you. Juls

**Comment by carl-hamlin** [comment]
Your assessment is exactly correct, Julia - Aries received his DHLPP well before we started tracking vaccines in BARKS, so he has the old-style, untracked line item on his chart. As soon as he receives a new DHLPP vaccine, BARKS will begin tracking it correctly.
