### ISSUE TITLE
Selective Printing: Vaccine History

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#706]
Good afternoon Carl...I know you are not busy enough, but would like to see if this is a possibility.
Would like to be able to print off the Client Name/address info, Animal Name, and JUST their Vaccine History.  If this is possible.
Thanks so much.

**Comment by carl-hamlin** [comment]
Same as with telephone number search - when you have a minute, please flesh out how you'd like this to work in the interface.

**Comment by julsneves** [comment]
Loren and I discussed and we would like to see an option (under the pet) in the VISIT dropdown menu that says VACCINE HISTORY.  This would pull up ANY and ALL vaccines given to a pet with most recent at top of list (if possible).
This will serve two purposes; 1 we can pull up info very quickly when another vet office calls; and 2 we can print JUST the Vaccine history without all of the detailed doctor notes attached, for the purposes of Boarding, Grooming, etc.

**Comment by carl-hamlin** [comment]
K. I'll look into this. Might be a minute - this isn't a trivial ask, but I see why you need it.

**Comment by carl-hamlin** [comment]
commit 7e117c0338a1c35639a8bb7a905a1334512cf756 (HEAD -> e.706, origin/e.706)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon May 9 12:30:02 2022 -0700

    Enhancement 706: Vaccine History
    
    First pass at printable vaccine histories.

**Comment by carl-hamlin** [comment]
This is finished, but per Dr. Simko's request will not be deployed until I can be in the office for a few days to handle settling impacts.

**Comment by carl-hamlin** [comment]
Deployed.

I'm closing the issue, and will re-open if things start to go *click* when they should be going *whirr*.
