### ISSUE TITLE
Search Criterion: Phone Number

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#707]
When searching for a client when we are not sure of the name or spelling of the name...it would be very helpful to be able to search by Client Phone Number.
Thank you.

**Comment by carl-hamlin** [comment]
When you have a minute, please flesh out how you'd like this to work in the interface.

**Comment by carl-hamlin** [comment]
I'll check back on this in two weeks. If it's not been fleshed out by then I'll close it out and get it off the agenda.

**Comment by julsneves** [comment]
We would like to see a Search Phone button next to the Search Human button on the Caretakers Screen. We would like to enter the 10 digits and have it bring up corresponding client(s).  If more than one client with this phone number it would be great if we could see all of the clients with that number and then be able to select the correct one.

**Comment by carl-hamlin** [comment]
Gotcha. Same as with vaccines - that sounds simple, but in practice may involve having to implement an entirely new table on the server. I'll roll it around and see if I can come up with cheap design ideas for this feature.

**Comment by carl-hamlin** [comment]
commit 42ed13c13753826eaa416bf85bc03c9f9c4bac2a (HEAD -> e.707, origin/e.707)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu May 5 16:39:57 2022 -0700

    Enhancement 707: Search by Phone
    
    First pass at search by phone.

**Comment by tlutzi** [comment]
Thanks Carl!
