### ISSUE TITLE
Duplicate Client/Pet

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#708]
Joey McClure has two accounts in our system. 
CID 4053 is Joey McClure. With no space between the Mc and the Clure. Owning Shadow AID 9221.
CID 4060 is Joey Mc Clure. with a space between the Mc and Clure. with pet Shadow AID 9228.
Please remove CID 4060 and AID 9228. This account has no visits.

**Comment by carl-hamlin** [comment]
Fixed
