### ISSUE TITLE
Intact Status

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#71]
Can you please make a feature that will automatically change  the patients sexual reproduction status from intact to spayed/netured once the have had surgery !!

**Comment by carl-hamlin** [comment]
commit 04892900725d1d0aef9cd92c6c094c1079acccf3 (HEAD -> record.keeping, origin/record.keeping, origin/e.71, origin/HEAD, e.71)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon May 11 13:39:40 2020 -0700

    Enhancement 71: Toggle Intact Status
    
    Intact bit now gets toggled off when a spay or neuter visit is
    finalized.
