### ISSUE TITLE
Add Phone Number for Kathy Thomas

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#712]
Carl I input this new client today 4.18.22 and must have put in the dashes in the phone number  Please add  5105204407
The weird part is that BARKS did not show a Client ID number??  So just in case it is the owner of AID 9514

**Comment by carl-hamlin** [comment]
Fixed. Please don't put anything in the phone number field that isn't numbers. When I've put out enough fire that I have a minute to breathe, I'll sanitize the inputs for the phone number field so this will stop being such a problem, but in the meantime, I need you guys to please stop putting things that aren't numbers in the field. Thanks!
