### ISSUE TITLE
More Weirdness in BARKS

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#714]
Doctor had me add Advantage 2 to Thomi Ward CID 3710 for her cat Licorice (Lil Black Kitty) it was $14.
I finalized and told Julia to go ahead and bill out the client. But when I came back in the building, Julia said it wasn't in yet, which I had just posted as I left. But, Yes in fact it was added and somehow paid without a payment? It has a Zero Balance but does not show any payments being made and is not in End of day. We did end up taking the money from the client.

**Comment by carl-hamlin** [comment]
Thank you. This *is* a weird one. At first, I figured this was going to be a case of a double-linked pet and that we just had the wrong CID on the payment, but nope - there was legitimately no payment whatsoever attached to the visit, and yet... zero balance. There's now a payment attached to the visit. Please keep an eye out for instances of this issue - this is a BIG fucking problem.
