### ISSUE TITLE
Rabies Tag Number/Certificate

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#72]
Legally our software has to generate a rabies certificate with each patient we administer a rabies vaccine to. Items that must be included on the certificate 
1. Our Clinic Name, address phone number
2. Veterinarian 
3. Date of vaccine administration 
4. Length of vaccine--1 year or 3 year 
5. Manufacturer, Lot/Serial Number, Killed/Modified live/Recumbent Vaccine
6. Rabies Tag number-->The receptionists will complete that info according to the physical tag provided to  the client 
7. Clients Info, Including address, and phone number
8. Patient Name and signalment, (species, breed, age, sex, color, weight)

**Comment by carl-hamlin** [comment]
commit c5873a78c440c2abc01120429f8254bb12f29867 (HEAD -> enhancement.72)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Wed Jul 3 10:13:17 2019 -0700

    Enhancement 72:
    
    Rudimentary rabies certificates may now be printed.
