### ISSUE TITLE
Balance on Account

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#722]
Susan Cowen CID 3806
Has a $13.00 balance on her deceased pet, Max. Are we supposed to charge her for this? or is this from the price change.

**Comment by carl-hamlin** [comment]
I'm not sure what you mean when you say 'from the price change'. Can you clarify, please?

**Comment by lwilsonbooth** [comment]
Yes! So after you had updated the pricings of our procedures and drugs, not the last time, but the time before that, it was before you had hired Julia, We had had this problem before where there was small change and some under $15.00 charges on certain client accounts. Like we had 1 client with an odd amount of change left on their account and you had told me that it must have been from when you had changed prices and it didn't format or something..
I cannot recall exactly
So I was just wondering if we needed to bring it up and ask the client if they paid in full when we euthanized their dog

**Comment by carl-hamlin** [comment]
Gotcha.

Strangely enough, when I load Ms. Cowen, there's no balance on her account. Please let me know if you're still seeing that, and if not, I'll close this issue.

**Comment by lwilsonbooth** [comment]
How strange indeed! It is gone, and I checked with both Teri and Julia. Julia only took $80.00 by check for her visit and meds today. I swear it was there this morning or I wouldn't have bothered you, Thank You anyways for making it go away.

**Comment by carl-hamlin** [comment]
The Magic Touch, I guess. I'm closing the issue.
