### ISSUE TITLE
Bad Balance Return Arithmetic in Line Item Removal

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#732]
Brent Redd CID 3022 needed canine 2 bottles of advantage2 small dog 
At first they were unsure if they wanted the whole box or just a single dose, so I added both to the invoice to tell them the price, when removing one on the items, the other zeroed out. 
This happened twice, The second time was after this on the same client, I added both single doses and finalized, but when I scrolled to the top of the page it had a zero balance as if the client had already paid, but there was no payment made.

**Comment by carl-hamlin** [comment]
Well, shit. It re-surfaced.

I was able to verify with Loren that visit 28169 reliably zeroed when a line item was removed. She says she's seen it happen under those circumstances before as well.

Examination with breakpoints showed incorrect return arithmetic after line item removal. Let's have a better look at this problem.

**Comment by carl-hamlin** [comment]
I've been able to reliable replicate this on Donut's old account. Steps to replicate:

1. Enter 'Advantage II Small Dog', quantity 1
2. Enter 'Advantage II Small Dog', quantity 0.25
3. Remove 'Advantage II Small Dog', quantity 1

Visit balance will zero.

**Comment by carl-hamlin** [comment]
commit 5f0291f296888019d294c4356a0994a1c2de4d2f (HEAD -> record.keeping, origin/record.keeping, origin/b.732, origin/HEAD, b.732)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Aug 29 14:04:10 2022 -0700

    Bug 732: Bad Arithmetic Return While Removing Line Items from Visits
    
    This is one of a few issues that arise from duplicate functions
    in the codebase.
    
    Due to ridiculousness surrounding the first year of development,
    there are a few different places in the codebase where visit
    totals are tallied, and removal of line items was one of them. The
    pitfalls of unreconciled technical debt.
    
    Fortunately, there's an accurate tally mechanism that closely
    follows execution of the line item removal code in the middle
    tier, so fixing this issue was super simple once I knew what was
    causing it - I just removed the superfluous tally mechanism and
    let the main, big, accurate one do the whole job on the client
    side. Done in time for tea and crumpets.
    
    I'm wasted here, I tell you. Wasted.
