### ISSUE TITLE
Client Account Correction - Please see details

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#747]
Carl this was apparently a problem from before I ever started.  I can not access the original and I think it best to start over anyway.
Client #2742 Debra Olguin is the CORRECT Client info
      She has four animals Maya 6419; Mattie 9790; Blue 6606; and Starla 8396

Client was previously entered with last name spelled OLQUIN...this is wrong.  I have linked the animals from this account to the CORRECT account #2742.
Can we DELETE the incorrect account if animals exist attached to it?  Or can we at least put a different Name/Title to that one?  Like maybe INCORRECT ACCOUNT???

Client VERY UPSET.

**Comment by carl-hamlin** [comment]
Caretaker #2742 has been eliminated from the database.

We can, of course, remove clients with animals linked to their accounts. It's a pain in the ass to do so, especially when payments have been posted to the erroneous account, but it can absolutely been done, and has been done in this case.

I'll be around for the full story of why this was so upsetting to Ms. Olguin - I have a feeling that bit should probably not be committed to print.
