### ISSUE TITLE
Delete Meds not picked up  CID:  2280

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#755]
Client shows balance of $61 from VID 22069 on 1.7.22; Client had been getting insulin from Chewy.  Dog passed in February 2022.  
 o does not believe they ever picked this up.  Do you think we can get rid of balance?  
Let me know please.  Thanks, Juls

**Comment by carl-hamlin** [comment]
Normally, when something like this happens, it's a slam dunk - they never picked up the medication, never paid for it, we don't have to keep the record of the request. Hell with 'em; we can smoke the whole visit and forget about it with a clear conscience.

In this instance, however, Dr. Simko had written some notes on the visit, which always complicates things. After conferring with her on the matter, we determined to remove the medication from the visit and leave the notes. Please review the fix - I'm closing this issue, but if you lot can think of a reason that this solution is inadequate, I'd like to hear about it, and may potentially re-open this one for further pursuit.
