### ISSUE TITLE
Smoking Old RX's

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#759]
There needs to be a way for DR to remove old prescriptions from client's accounts. For example if a client was given a certain amount the first time, the refills stay at that amount but when the client asks for 2 months or more of medication, the receptionist have no way of knowing which one to click for refills and more often then not, we click the wrong one

**Comment by julsneves** [comment]
Maybe the system could show us not just the medication name but mg and how many (ie #30, 60 etc)

**Comment by carl-hamlin** [comment]
Hiya, Julia. The prescription titles are written by the prescribing doctor. BARKS doesn't generate those itself.

**Comment by julsneves** [comment]
Hiya Carl…ohhhh. Ok so it would be Dr that would have to put the info in.  Gotcha!

**Comment by carl-hamlin** [comment]
commit a6559750da1ff78477a6b54667d50fecf323ea97 (HEAD -> record.keeping, origin/record.keeping, origin/e.759, origin/HEAD, e.759)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Fri Jul 29 14:17:46 2022 -0700

    Enhancement 759: Removal of Prescriptions
    
    Doctors and admins may now remove prescriptions from the refill
    interface.

**Comment by carl-hamlin** [comment]
Julia, we could make the prescription refill interface display that information if it would be helpful. If you'd like to see that happen, please construct a new issue and describe in detail how you'd like to see that implemented, and we'll start the discussion.
