### ISSUE TITLE
Animals Failing to Populate After Rabies Certificate (Highly Intermittent)

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#760]
Twice this week I've had animals glitch out
for example, a client brings in 2 animals for rabies shots and so far it seems like if DR is still working on her notes when i print the first rabies certificate, when i load the second animal the first one stays in the slot and if i try to print the second dog's certificate the first one gets printed.
Also the name will appear without an AID number

**Comment by carl-hamlin** [comment]
Loren. This is *not* a data munge.

**Comment by carl-hamlin** [comment]
We haven't seen this behaviour is some time, so I'm closing the issue, and will re-open it if it re-surfaces.
