### ISSUE TITLE
Credential Edit or Delete

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#773]
Hi Carl,  Is there anyway we can either DELETE old credentials or at least EDIT them?  If not, Can we make it so the most recent populates at top?
Reason:  We have to keep Changing/Updating the Passwords (ie CareCredit)  

Let me know your thoughts, please.

**Comment by carl-hamlin** [comment]
I concur. Work will be logged on issue #340 for posterity.

**Comment by carl-hamlin** [comment]
Issue has been addressed in #340. Closing.
