### ISSUE TITLE
Caretaker Last Name Appearing as Random Words in Caretaker Banner (Highly Intermittent)

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#774]
On August 3rd I had added a new client to BARKS and when I loaded the caretaker it showed all the information I added, but the last name had changed. This is happening again, Teri added an appointment to an existing client in BARKS and when loaded the last name changed again.
First client was Robert Stange CID 4472. Second client was David Lakin CID 2981.

The slot where you type the client name was correct and the animals cared for was correct, but the blue banner at the top hold a completely different name. Both times.

**Comment by lwilsonbooth** [comment]
This has happened again. Edda Engles CID 3224 appearing as Edda English .

**Comment by carl-hamlin** [comment]
So it's been more than a month and this shit hasn't happened since. I'm going to close the issue and we'll re-open it if we see it again.
