### ISSUE TITLE
Refund Needed for Client 7023

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#793]
Shirly Silveria brought dog into clinic on 8/25/22; she had an **outstanding balance of $50 from 9/30/2020;** she paid it even though she knew she had paid it already.
Her son came in today with proof of payment (copy of credit card statement showing it had been paid...only difference is that the amount paid that day in 2020 was only $45.44...but I'm sure exam charges would have been different back then).

Can you please issue a refund check on your return?  Thank you, Juls

I tried to attach copies of documents here...but "grrrrrrrr" could not make it happen.  So, I am texting them to you now.

**Comment by carl-hamlin** [comment]
I have issued her a check with our apologies for the mixup.

**Comment by julsneves** [comment]
Thank you, Carl.
