### ISSUE TITLE
Dog Breed 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#797]
Please add Turkish Kangal into BARKS.

**Comment by carl-hamlin** [comment]
Holy shit! A legitimate ask for a real breed that we didn't have in the database! I should go buy a lottery ticket!

It's in there. I'm leaving this open until someone either provides me with an animal ID to which this breed needs to be applied, or informs me that they've applied it to the animal in need of it.

**Comment by carl-hamlin** [comment]
OK, maybe not so legitimate. I'm going to give this one more week, and if I don't hear from someone as to who needed it and why, I'm pulling the breed and closing this issue.

**Comment by lwilsonbooth** [comment]
Thank You for adding that in, I've changed the dog to the correct breed.
