### ISSUE TITLE
Redundant Loading in RK Element Selection Code

### ISSUE THREAD

**Issue by carl-hamlin** [carl-hamlin/barks#801]
While putting together the nascent record disposition code, I've discovered that in certain instances, RK elements are being loaded redundantly. Let's kick that behaviour in the ass and speed up load times.

**Comment by carl-hamlin** [comment]
commit 22748cb2373bd57805dd868349ceba1bb3ac37f9 (HEAD -> record.keeping, origin/record.keeping, origin/b.801, origin/HEAD, b.801)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Tue Oct 4 18:01:32 2022 -0700

    Bug 801: Redundant Loading in RK Element Selection
    
    RK Element Selection no longer loads redundantly.

**Comment by julsneves** [comment]
I’m not sure who entered the animal; but it was spelled incorrectly…per owner.
