### ISSUE TITLE
Phone Number Field Missing

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#802]
Please investigate the disappearance of Tina Lindow's phone number in BARKS.
I went to add her pet's appointment in BARKS and noticed she had no space for a phone number to be added.
Current number for client is 2095844472
Please add when you can, Thanks

**Comment by carl-hamlin** [comment]
Ms. Lindow, as it turns out, never had a phone number to begin with.

The way the client software works, nobody is supposed to ever be able to get in without a telephone number. Tina Lindow somehow did. She now has a telephone number, however, and all is right with the world.
