### ISSUE TITLE
Remove Duplicate Animal ID

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#804]
OK Carl...this one is probably on me...I entered client CID 4565 (forgot to hit submit); so had to re-enter client (after checking to see she was NOT in system).  I then Linked the animal AID 8994.  Seemed fine...but the AID shows up twice under this client now??
Just sent picture to your phone.

Sorry!

**Comment by julsneves** [comment]
P.S.   Maybe we need a label that says "DUH" for some of us.  LOL

**Comment by carl-hamlin** [comment]
This one was truly bizarre. There were two records in the known associations aggregate, both of which had identical timestamps: '2022-10-03 22:39:59'. That's a hell of a thing to arrange, and I hope I can track this one down. This should be very interesting.

In the meantime, the surface level symptomology has been addressed. Closing issue.
