### ISSUE TITLE
Delete Duplicate Client CID 4585

### ISSUE THREAD

**Issue by julsneves** [carl-hamlin/barks#815]
Client entered as "Cortening" ;  this was wrong...Its Corpening and she was already in system.  Thank you. My fault. 
Good news...I collected on old balances  :-)

**Comment by carl-hamlin** [comment]
Julia, when you need me to remove caretakers, I need the CID for both the erroneously entered record, and the correct record.

**Comment by carl-hamlin** [comment]
Fixed
