### ISSUE TITLE
Coat Pattern?

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#819]
Fiona Bennett CID 1061 
client is complaining again about not having Grizzle coat pattern listed on her pets.

**Comment by carl-hamlin** [comment]
Client may take her complaint firmly in both hands, fold it until it is almost exclusively comprised of sharp corners, and force it with as much strength as her ailing body can muster, deep into her diseased rectum, where it shall hopefully fester and cause us never, ever, ever to have to deal with her sorry ass again.

Thank you for reporting this issue. We are, of course, not going to add a bullshit coat pattern to the database and reduce our already dodgy data hygiene for the sake of quieting one harridan voice. If this is really that large an issue, she's more than welcome to take her pets to a competing veterinarian. Closing issue 'wont fix'.
