### ISSUE TITLE
Incorrect Billing 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#823]
David Schomber called to pay his remaining balance for Oliver. He said he owed $54.00 and the invoice in the system showed a $75.00 balance.
I had the client read off his invoice receipt and the Bloodwork we did that day came to $180 (our system showed $200) and the Recheck Exam was $31 (ours showed $34). Charged the client the $54.00
CID 1030
AID 10160
VID 29372

**Comment by carl-hamlin** [comment]
Fixed
