### ISSUE TITLE
Delete Duplicate

### ISSUE THREAD

**Issue by tlutzi** [carl-hamlin/barks#826]
Please delete ID4655 duplicate, Internet lag.

**Comment by carl-hamlin** [comment]
Teri, I have *NO* idea what you're asking me to do. Is this a visit ID, and animal ID, a caretaker ID? What are we talking about?

**Comment by tlutzi** [comment]
It's a caretaker ID.  Thank you

**Comment by carl-hamlin** [comment]
Fixed
