### ISSUE TITLE
Remove Item from invoice

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#839]
Shannon Weber CID 934 just picked up Gunner's (AID 2902) apoquel.
I had to click the refill button to refill the meds, although there where 2 options to refill the apoquel
one was for 30 tablets and the other for 60.
she needed the 60 count. There is no way for me to tell which is which so I  just clicked one. It ended up being the one for 30 and not the 60. So I need you to remove the extra refill prescription from her account since she isn't buying it.

**Comment by carl-hamlin** [comment]
Fixed
