### ISSUE TITLE
Found Duplicate Client 

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#841]
Brandy Farrell CID 2490 and Brandi Farrell CID 2719 
same person, same address and phone number.
Simba AID 6117 is linked to both accounts.

**Comment by carl-hamlin** [comment]
Which one is spelled correctly?

**Comment by lwilsonbooth** [comment]
Good question, I will call and ask.

**Comment by carl-hamlin** [comment]
After several months, it comes out that the client's husband has been in, and spelled her name with an 'I'. I've removed caretaker entry 2490.
