### ISSUE TITLE
Payment Posting Error Fix

### ISSUE THREAD

**Issue by lwilsonbooth** [carl-hamlin/barks#853]
Is there a way for BARKS to have an empty space for the Cash/Credit/Check option, I feel like if it were empty it would slow me down a bit to make sure I make no more errors posting payments.

**Comment by carl-hamlin** [comment]
commit 41c22f1db382655abdba57c1f4fba783a861d733 (origin/e.853, e.853)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu Feb 16 15:38:15 2023 -0800

    Enhancement 853: Payment Posting Fuckup Fix
    
    Payment types now include Martian Cheese Wedges. Should fix the
    'too fast' issues.
