### ISSUE TITLE
Add Alerts to Patient Info

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#86]
please make it possible that we can add alerts for reactions to drugs/vaccines and or chronic illnesses.

**Comment by carl-hamlin** [comment]
Heya, Lenore. Please list in detail what alerts you'd like to see.

**Comment by Lenorebarton** [comment]
Vaccine Reactor
Drug allergy
Dog/Cat Agrressive

**Comment by carl-hamlin** [comment]
Caution is already in there - I'll look into adding Vaccine Reactor and Drug Allergy.

**Comment by carl-hamlin** [comment]
This issue has been subsumed by enhancement #607.
