### ISSUE TITLE
Invoice Totals are incorrect

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#88]
Most invoices are showing incorrect total  after payments have been made

**Comment by carl-hamlin** [comment]
commit 35c2bf6237db5cb562f9eba7ab45500ad1c98e05
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 08:29:56 2019 -0700

    Enhancement 85:
    
    Visit balances are now checked and maintained during caretaker
    search in addition to being checked and maintained during line
    item entry.
    
    We'll probably get rid of the line item entry check - it's
    considerably more complex and at this point doesn't add value.

**Comment by carl-hamlin** [comment]
commit e2fb01659e219e17d0a1e0bc0eb6142ba64a95aa
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 09:44:19 2019 -0700

    Enhancement.85
    
    Second half of the math fix required before I get startd on the
    aggregation interface.

**Comment by carl-hamlin** [comment]
commit d46eccbecd93383562a06ad2ffe85698c16f7116
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 10:27:38 2019 -0700

    Enhancement 85:
    
    Math fix now takes payments into account.

**Comment by carl-hamlin** [comment]
commit 797825bf80d8e6f14b0a3335b427f50431c04aa4
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 11:19:49 2019 -0700

    Enhancement 85:
    
    System now corrects balances that go below 0.

**Comment by carl-hamlin** [comment]
commit 6f117c71de0bf8453120ee62c1aaecf071ddc5fc
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 16:38:02 2019 -0700

    Enhancement 85:
    
    Line Items now have their values stored in their respective
    records so as not to have to be recalculated at every load.
    
    Additionally, this allows for client balances to remain static
    through price changes.

**Comment by carl-hamlin** [comment]
commit ccbac9037de59706f70989df93794beb47017c56
Merge: 3aa6097 6f117c7
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jul 22 19:49:48 2019 -0700

    Merge branch 'enhancement.85' into record.keeping
