### ISSUE TITLE
Appointments: Deletion and Date Edits

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#93]
On our side we are still not able to edit or delete any appointments

**Comment by carl-hamlin** [comment]
Yep. The code is in for yu to be able to remove appointments that meet the following criteria:

1. You made the appointment.
2. Nobody else has added anything to the appointment.

I'll do some testing and see if there''s a logic error preventing that button from showing up for you guys.

**Comment by carl-hamlin** [comment]
Fixed in Enhancement 77.
