### ISSUE TITLE
Animal Loading Issue 

### ISSUE THREAD

**Issue by Lenorebarton** [carl-hamlin/barks#94]
when posting for multiple patients, after collecting $$ and printing invoices, i am unable to loed 2nd / 3rd patient without resetting

**Comment by carl-hamlin** [comment]
What happens when you try? Do yu get an error, or does it hang up at a loading screen, or something else?

**Comment by Lenorebarton** [comment]
No error message just loads last patient over again

**Comment by Lenorebarton** [comment]
I have t completely reset BARKs in between patients.

**Comment by carl-hamlin** [comment]
Is this still a live issue? There have been multiple changes to the way clients load between now and July 23rd. Please let me know.

**Comment by carl-hamlin** [comment]
In the absence of an answer to my question on the 16th, I'm going to assume this is no longer an issue, and close the bug.
