### ISSUE TITLE
Vaccine Tracking 

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#95]
We need to have the ability to track vaccine status on patients. Barks needs to be able to produce recommendations and due dates on patient vaccines. We also need to be able to print out reminders to send to clients.

**Comment by Lenorebarton** [comment]
Along with the ability to track vaccines we need to be able to generate reminders for them.  This is a $$$ generating service.  Clients have come to rely on the reminders to keep their pets current and healthy.

**Comment by carl-hamlin** [comment]
commit d960ebf5a97503cb74e6be3052f3ca5a5d5b576b (origin/e.95, e.95)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu May 7 17:58:37 2020 -0700

    Enhancement 95: Vaccine Tracking
    
    Vaccines are now tracked.

**Comment by carl-hamlin** [comment]
commit 752cab58dbed8f8f3f1aa461dd764a3d8d53f316 (origin/e.95, e.95)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Thu May 14 17:32:55 2020 -0700

    Enhancement 95: Vaccine Tracking
    
    Vaccine Reminders are in.

**Comment by carl-hamlin** [comment]
The same vaccine is showing up multiple times on animal headers.

The header and reminder system should only operate on the latest instance of the vaccine.

**Comment by carl-hamlin** [comment]
commit a1959709b23f06dc08012801923d320f188cfcbb (origin/e.95, e.95)
Author: Carlisle T. Hamlin <hamlin.carlisle@gmx.com>
Date:   Mon Jun 29 16:16:45 2020 -0700

    Enhancement 95: Vaccine Tracking
    
    Moved misplaced variable 'vnames' which was clearing per visit
    rather than per animal. Vaccines no longer double up on the chart.
