### ISSUE TITLE
Editing of Patient & Client Names 

### ISSUE THREAD

**Issue by CMaxeyRVT** [carl-hamlin/barks#96]
We need the ability to edit client and patient info.
Including being able to delete duplicate accounts if necessary

**Comment by carl-hamlin** [comment]
Editing client and patient names is not a thing that will ever happen. My recommendation would be for staff to hone data entry skills - folk who enter data correctly the first time will retain their value a lot more than folks who don't, and when I *do* have to make a correction on the back end for an avoidable reason, you can bet your ass I'm taking note of who entered the bad data.

Additionally, deleting client accounts, for whatever reason, will always have an incredibly tedious security gateway involved. Staff will never just have a button to make that happen, but there may be a process that's a little more automated than 'Text Carl and ask him to do it'. For the foreseeable future, however, the safe assumption will be that if an account needs removing, it's going to involve a discussion with me.

We're still working on how we want to handle that in the future.
